services:
  krakend:
    image: devopsfaith/krakend
    ports:
      - "8081:8080"
    volumes:
      - "./krakend.json:/etc/krakend/krakend.json"
    depends_on:
      - user-service
      - product-service

  user-service:
    build: ./user-service
    ports:
      - "8002:8000"

  product-service:
    build: ./product-service
    ports:
      - "8003:8000"